export enum ActionType {
  UPDATE_WIDTH = "UPDATE_WIDTH",
  UPDATE_HEIGHT = "UPDATE_HEIGHT",
  UPDATE_LAYERCOUNT = "UPDATE_LAYERCOUNT",
  UPDATE_TURNCOUNT = "UPDATE_TURNCOUNT",
  UPDATE_VARIANCE = "UPDATE_VARIANCE",
  UPDATE_COLOR_SELECTION = "UPDATE_COLOR_SELECTION",
  UPDATE_SVG = "UPDATE_SVG"
}

export default ActionType;
